### ISSUE TITLE
Same form on multiple pages

### ISSUE THREAD

**Issue by jaffa-cake** [pinceladasdaweb/Ajax-PHP-MySQL-Newsletter#1]
Hi,
I'm trying to have this form at the bottom of every page, but it only works on my index.html. What do I need to do to get it to work on all pages?

**Comment by pinceladasdaweb** [comment]
Which browser are you using? Can you send a screenshot of the error?

**Comment by jaffa-cake** [comment]
I'm using Firefox. There isn't exactly an error. It just redirects me to a blank page. The URL shows it's send.php, but it's all blank.

**Comment by jaffa-cake** [comment]
If I don't enter an email address, the blank page displays this:
{"status":"error","message":"The email address field must not be blank"}

**Comment by jaffa-cake** [comment]
I tried it again, and it actually does enter the email in the database - the only problem is that it doesn't display the message in the response div, but redirects to a new page. I just can't figure out why that only works on the index page.

**Comment by pinceladasdaweb** [comment]
I believe that on other pages the JavaScript URL is incorrect, so Ajax is not running. Please, with the firefox console open, refresh the page and see if there is a JavaScript error that is not found.

**Comment by jaffa-cake** [comment]
Thanks for you help. I didn't make any changes, but now it's working. Maybe it was just a caching issues. I'm sorry to bother you!
