### ISSUE TITLE
Stops working when adding extra field

### ISSUE THREAD

**Issue by purgeru** [pinceladasdaweb/Ajax-PHP-MySQL-Newsletter#2]
Hi, added one extra field but then form stops working, can I ask you if you have any idea why it throws me an error? Thank you in advance.
[fbsignup.zip](https://github.com/pinceladasdaweb/Ajax-PHP-MySQL-Newsletter/files/706171/fbsignup.zip)

**Comment by pinceladasdaweb** [comment]
Open file:

https://github.com/pinceladasdaweb/Ajax-PHP-MySQL-Newsletter/blob/master/inc/Newsletter.class.php

And add the following code:

``
private static $name;
``

The file should look like this:

``
class Newsletter
{
    private static $name;
    private static $email;
``

**Comment by purgeru** [comment]
Thank you for the help, but there is still something that throws an error ;(

**Comment by pinceladasdaweb** [comment]
Is the error occurring in PHP or JavaScript?

**Comment by purgeru** [comment]
Page is loading, so I guess the error is ocurring in JavaScript.

**Comment by pinceladasdaweb** [comment]
Try to observe in the console in the browser if it shows some error. If there is any, keep a print of it here, please.
